### ISSUE TITLE
Web interface does not use maximal position for motors

### ISSUE THREAD

**Issue by SloMusti** [IRNAS/koruza-pi#2]
Web interface in  koruza-pi/package/koruza/webui/assets/scripts/drivers/motors.js implements hardcoded maximal positions for motors, but should use the ones defined in  koruza-pi/package/koruza/config/koruza.conf

**Comment by kostko** [comment]
Fixed, just be sure to specify configuration values as numbers in the `koruza.conf` JSON (do not make values strings by putting quotes around them).
