### ISSUE TITLE
Device name should change hostname and dns broadcast

### ISSUE THREAD

**Issue by SloMusti** [IRNAS/koruza-pi#4]
Device name in settings should change the hostname of the device to whichever one is set and change the dns broadcast, such that it works by <hostname>.local allowing for multiple units to co-exist on the same network

**Comment by kostko** [comment]
Is it ok if it changes on reboot?
On 8 Jan 2016 12:07 pm, SloMusti notifications@github.com wrote:Assigned #4 to @kostko.

**Comment by SloMusti** [comment]
Doing this after reboot is ok. Add reboot button under settings.
